### ISSUE TITLE
使用牛子深度排行报错

### ISSUE THREAD

**Issue by PackageInstaller** [molanp/zhenxun_plugin_niuniu#1]
最新版真寻，系统是Arch Linux
![image](https://user-images.githubusercontent.com/80018096/217422953-08fe2306-4c4c-43de-a782-10688411c9d2.png)

**Comment by PackageInstaller** [comment]
是群里没有负数长度的原因，要是能加个反馈就好了

**Comment by molanp** [comment]
正在修改

**Comment by molanp** [comment]
44d370e
