### ISSUE TITLE
太棒了，👨‍❤️‍👨快乐小游戏，可以给机器人加牛牛，jj@两次机器人就可以击剑了

### ISSUE THREAD

**Issue by LaffeyLa** [molanp/zhenxun_plugin_niuniu#3]
就想悄悄地问下能不能加个让某个人击剑必胜的代码（

**Comment by molanp** [comment]
emmm这个涉及到改底层判断代码（
以后可能会添加这个强制成功的命令(

如果需要的话可以偷偷去`data/long.json`里修改别人牛子的长度/深度，json文件key1为群号，key2为用户QQ号，key2的value类型为float

**Comment by molanp** [comment]
目前思路是通过命令添加的强制标签判断
```py
if jj.label == True:
   ...more...
```
```py
if hit_glue.lable == True:
   ...more...
```

**Comment by LaffeyLa** [comment]
> 目前思路是通过命令添加的强制标签判断
> 
> ```python
> if jj.label == True:
>    ...more...
> ```
> 
> ```python
> if hit_glue.lable == True:
>    ...more...
> ```



> 目前思路是通过命令添加的强制标签判断
> 
> ```python
> if jj.label == True:
>    ...more...
> ```
> 
> ```python
> if hit_glue.lable == True:
>    ...more...
> ```

加油，一定能行
