### ISSUE TITLE
希望可以拓展更多的玩法

### ISSUE THREAD

**Issue by lonelyenderman233** [molanp/zhenxun_plugin_niuniu#4]
抛砖隐玉，列举几个想到的新玩法：

- 小牛牛与大牛牛击剑有30%概率反杀，反杀后奖励翻倍
- 击剑长度奖励根据对方与自身长度总和比例计算，而非固定随机数值，比如击剑奖励数值为双方绝对值长度总和的10%~20%(随机值)
- 增加魅魔(<-100)与牛头人(>100)称号
- 牛牛长度在0—100之间的与魅魔击剑有概率被吞噬成0，-100—0与魅魔击剑继续走原来逻辑
- 牛牛长度-100—0的与牛头人击剑有概率被补平到0，0—100与牛头人击剑继续走原来逻辑

其中1和3我已经在您的基础上实现了，其余功能需要大改脚本，我py学的一塌糊涂，怕改乱了。。。

**Comment by molanp** [comment]
> - 小牛牛与大牛牛击剑有30%概率反杀，反杀后奖励翻倍

这一个判断有过了
在156行，当对方比自己长时，55%概率逆袭，好像有点太高了，我去改一下(e73914d)

**Comment by molanp** [comment]
2 4 5判断称号还是考虑与 #3 使用一个标签， #3 的标签改为 `jj.lable['force']` ， 称呼判断代码使用示例
```python
if jj.lable['title'] == "mm" && 0.0 <= my_long <= 100.0:
   ...
elif jj.lable['title'] == "ntr" && -100.0 <= my_long <= 0.0:
   ...
else:
   ...
```
你的想法很不错，我会在下周末对代码进行更改

**Comment by lonelyenderman233** [comment]
hao

> 2 4 5判断称号还是考虑与 #3 使用一个标签， #3 的标签改为 `jj.lable['force']` ， 称呼判断代码使用示例
> 
> ```python
> if jj.lable['title'] == "mm" && 0.0 <= my_long <= 100.0:
>    ...
> elif jj.lable['title'] == "ntr" && -100.0 <= my_long <= 0.0:
>    ...
> else:
>    ...
> ```
> 
> 你的想法很不错，我会在下周末对代码进行更改

好的，加标签的思路确实不错，我本来想的是直接判断长度来确定称号，但那样的话代码逻辑看起来就很乱了
