### ISSUE TITLE
拓展玩法+1

### ISSUE THREAD

**Issue by kuai364354200** [molanp/zhenxun_plugin_niuniu#5]
有几个已经变成无底黑洞的“女”群友嚷嚷着要注销牛牛，于是我：
![图片](https://user-images.githubusercontent.com/72508741/223640257-d9780285-a064-4e6c-9722-f9fcd718afa3.png)
![图片](https://user-images.githubusercontent.com/72508741/223640209-a0974f51-99d8-44ce-9d41-0455f3815d1a.png)
感觉可以思考一下如何补偿女孩子

**Comment by kuai364354200** [comment]
之前我稍微尝试了负数可玩性，把：
打胶=每天固定低保获得长度
击剑=掠夺他人长度
但是好像逐渐发展成网络暴力了，感觉不太好

**Comment by lonelyenderman233** [comment]
我感觉要解决长度歧视问题(大雾)，核心就是增强小牛牛和“女”群友的竞争力，比如负牛牛有几率将正牛牛吞噬归0什么的，各方有各方的专属技能和优势，主打一个公平~~竞鸡~~

**Comment by lonelyenderman233** [comment]
> 之前我稍微尝试了负数可玩性，把： 打胶=每天固定低保获得长度 击剑=掠夺他人长度 但是好像逐渐发展成网络暴力了，感觉不太好

我感觉要解决长度歧视问题(大雾)，核心就是增强小牛牛和“女”群友的竞争力，比如负牛牛有几率将正牛牛吞噬归0什么的，各方有各方的专属技能和优势，主打一个公平竞鸡
