### ISSUE TITLE
模块未找到

### ISSUE THREAD

**Issue by flower-knight** [molanp/zhenxun_plugin_niuniu#7]
兄啊，你是不是依赖没删干净啊，还是把until.py误删了。
![image](https://user-images.githubusercontent.com/75349850/224282809-7d45e438-5817-47b7-85c0-71782928b11f.png)

**Comment by molanp** [comment]
没删干净（）把第三行删了就行了

**Comment by molanp** [comment]
或者直接去下载release，刚更新
