### ISSUE TITLE
希望优化一下数值膨胀的问题，打胶彻底失去了它的意义

### ISSUE THREAD

**Issue by WuGuiliu** [molanp/zhenxun_plugin_niuniu#9]
![)5XF`6 SR{82`D(K4@%`T_E](https://user-images.githubusercontent.com/129304069/228579402-308e3dcc-924a-49ac-93b1-5488af1a2562.png)
![Q4IU P7L3SJ92JJ3IHU$B)7](https://user-images.githubusercontent.com/129304069/228577658-b5a7b5ab-ca01-458c-b9c0-c44ddc2c1fab.jpg)

**Comment by lonelyenderman233** [comment]
我焯，你这是什么数值爆炸

**Comment by molanp** [comment]
目前已发现这个问题
初步判断是`n的绝对值乘0的绝对值的浮点数`导致的这个问题

> 现在在研究如何解决

~~我的一个群里数据都到e+13了()~~

**Comment by molanp** [comment]
然后会提供超级用户命令对超过一百万的进行强制归平

**Comment by WuGuiliu** [comment]
> 然后会提供超级用户命令对超过一百万的进行强制归平

希望给超级用户加一个强制给别人注册牛子的功能

**Comment by WuGuiliu** [comment]
> > 然后会提供超级用户命令对超过一百万的进行强制归平
> 
> 希望给超级用户加一个强制给别人注册牛子的功能

草，不用了，直接在txt里复制别人qq号就行了

**Comment by lonelyenderman233** [comment]
> 

所以这个bug是怎么触发的，到目前为止我的四个群数值都是正常的。。。

**Comment by lonelyenderman233** [comment]
> 目前已发现这个问题 初步判断是`n的绝对值乘0的绝对值的浮点数`导致的这个问题
> 
> > 现在在研究如何解决
> 
> ~我的一个群里数据都到e+13了()~

所以这个bug是怎么触发的，到目前为止我的四个群数值都是正常的。。。

**Comment by WuGuiliu** [comment]
> > 目前已发现这个问题 初步判断是`n的绝对值乘0的绝对值的浮点数`导致的这个问题
> > > 现在在研究如何解决
> > 
> > 
> > ~我的一个群里数据都到e+13了()~
> 
> 所以这个bug是怎么触发的，到目前为止我的四个群数值都是正常的。。。

当一个人变成负数之后，其他所有人逮着他一个人薅，他就会越来越深，然后其他人就会越来越长。就算被魅魔吞了，只要jj成功一次就会立刻长回来。
结果就是，一群牛头人盯着一个魅魔疯狂薅。膨胀起来之后，牛头人和长度为0的jj必定平局。
我们已经发展到一群e+16了，魅魔就算把所有牛头人吞了也喂不饱，击剑是按比例增减的，而打胶只能做到10以内的增减，完全不够看。
现在就每隔一段时间人为重置一下，开新赛季。或者把唯一的负数改成正的，这样长度总量就固定了。
我建议，魅魔技能改成：吞噬对方长度的同时把对方同化成魅魔(深度为原数值的一半)，其他的算法再优化下。

**Comment by molanp** [comment]
更改前的意见征求：
是否对长度深度进行max/min限制？

**Comment by WuGuiliu** [comment]
> 更改前的意见征求： 是否对长度深度进行max/min限制？

可以限制，我觉得限制在1亿吧

**Comment by lonelyenderman233** [comment]
> > > 目前已发现这个问题 初步判断是`n的绝对值乘0的绝对值的浮点数`导致的这个问题
> > > > 现在在研究如何解决
> > > 
> > > 
> > > ~我的一个群里数据都到e+13了()~
> > 
> > 
> > 所以这个bug是怎么触发的，到目前为止我的四个群数值都是正常的。。。
> 
> 当一个人变成负数之后，其他所有人逮着他一个人薅，他就会越来越深，然后其他人就会越来越长。就算被魅魔吞了，只要jj成功一次就会立刻长回来。 结果就是，一群牛头人盯着一个魅魔疯狂薅。膨胀起来之后，牛头人和长度为0的jj必定平局。 我们已经发展到一群e+16了，魅魔就算把所有牛头人吞了也喂不饱，击剑是按比例增减的，而打胶只能做到10以内的增减，完全不够看。 现在就每隔一段时间人为重置一下，开新赛季。或者把唯一的负数改成正的，这样长度总量就固定了。 我建议，魅魔技能改成：吞噬对方长度的同时把对方同化成魅魔(深度为原数值的一半)，其他的算法再优化下。

原来如此，我是把魅魔和牛头人的专属技能改成只将对方归0且自身长度不变，相当于变相回收长度了，不然长度一直在产出，通货膨胀了属于是

**Comment by molanp** [comment]
119bb97

**Comment by molanp** [comment]
d635b6b
